# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/sergey/Загрузки/clion-2021.2.1/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/sergey/Загрузки/clion-2021.2.1/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sergey/Документы/DATA/CLion

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sergey/Документы/DATA/CLion

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/sergey/Загрузки/clion-2021.2.1/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/sergey/Загрузки/clion-2021.2.1/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergey/Документы/DATA/CLion/CMakeFiles /home/sergey/Документы/DATA/CLion//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergey/Документы/DATA/CLion/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CLion

# Build rule for target.
CLion: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CLion
.PHONY : CLion

# fast build rule for target.
CLion/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLion.dir/build.make CMakeFiles/CLion.dir/build
.PHONY : CLion/fast

#=============================================================================
# Target rules for targets named BaseClass

# Build rule for target.
BaseClass: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BaseClass
.PHONY : BaseClass

# fast build rule for target.
BaseClass/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/BaseClass/CMakeFiles/BaseClass.dir/build.make IEC61850/BaseClass/CMakeFiles/BaseClass.dir/build
.PHONY : BaseClass/fast

#=============================================================================
# Target rules for targets named BaseType

# Build rule for target.
BaseType: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BaseType
.PHONY : BaseType

# fast build rule for target.
BaseType/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/BaseType/CMakeFiles/BaseType.dir/build.make IEC61850/BaseType/CMakeFiles/BaseType.dir/build
.PHONY : BaseType/fast

#=============================================================================
# Target rules for targets named BaseVector

# Build rule for target.
BaseVector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BaseVector
.PHONY : BaseVector

# fast build rule for target.
BaseVector/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/BaseVector/CMakeFiles/BaseVector.dir/build.make IEC61850/BaseVector/CMakeFiles/BaseVector.dir/build
.PHONY : BaseVector/fast

#=============================================================================
# Target rules for targets named CMV

# Build rule for target.
CMV: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CMV
.PHONY : CMV

# fast build rule for target.
CMV/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Measure/CMV/CMakeFiles/CMV.dir/build.make IEC61850/DO/Measure/CMV/CMakeFiles/CMV.dir/build
.PHONY : CMV/fast

#=============================================================================
# Target rules for targets named DEL

# Build rule for target.
DEL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DEL
.PHONY : DEL

# fast build rule for target.
DEL/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Measure/DEL/CMakeFiles/DEL.dir/build.make IEC61850/DO/Measure/DEL/CMakeFiles/DEL.dir/build
.PHONY : DEL/fast

#=============================================================================
# Target rules for targets named HDEL

# Build rule for target.
HDEL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HDEL
.PHONY : HDEL

# fast build rule for target.
HDEL/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Measure/HDEL/CMakeFiles/HDEL.dir/build.make IEC61850/DO/Measure/HDEL/CMakeFiles/HDEL.dir/build
.PHONY : HDEL/fast

#=============================================================================
# Target rules for targets named HMV

# Build rule for target.
HMV: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HMV
.PHONY : HMV

# fast build rule for target.
HMV/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Measure/HMV/CMakeFiles/HMV.dir/build.make IEC61850/DO/Measure/HMV/CMakeFiles/HMV.dir/build
.PHONY : HMV/fast

#=============================================================================
# Target rules for targets named HWYE

# Build rule for target.
HWYE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HWYE
.PHONY : HWYE

# fast build rule for target.
HWYE/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Measure/HWYE/CMakeFiles/HWYE.dir/build.make IEC61850/DO/Measure/HWYE/CMakeFiles/HWYE.dir/build
.PHONY : HWYE/fast

#=============================================================================
# Target rules for targets named SAV

# Build rule for target.
SAV: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SAV
.PHONY : SAV

# fast build rule for target.
SAV/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Measure/SAV/CMakeFiles/SAV.dir/build.make IEC61850/DO/Measure/SAV/CMakeFiles/SAV.dir/build
.PHONY : SAV/fast

#=============================================================================
# Target rules for targets named Sequence

# Build rule for target.
Sequence: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Sequence
.PHONY : Sequence

# fast build rule for target.
Sequence/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Measure/Sequence/CMakeFiles/Sequence.dir/build.make IEC61850/DO/Measure/Sequence/CMakeFiles/Sequence.dir/build
.PHONY : Sequence/fast

#=============================================================================
# Target rules for targets named MV

# Build rule for target.
MV: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MV
.PHONY : MV

# fast build rule for target.
MV/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Measure/MV/CMakeFiles/MV.dir/build.make IEC61850/DO/Measure/MV/CMakeFiles/MV.dir/build
.PHONY : MV/fast

#=============================================================================
# Target rules for targets named WYE

# Build rule for target.
WYE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WYE
.PHONY : WYE

# fast build rule for target.
WYE/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Measure/WYE/CMakeFiles/WYE.dir/build.make IEC61850/DO/Measure/WYE/CMakeFiles/WYE.dir/build
.PHONY : WYE/fast

#=============================================================================
# Target rules for targets named ASG

# Build rule for target.
ASG: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ASG
.PHONY : ASG

# fast build rule for target.
ASG/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Settings/ASG/CMakeFiles/ASG.dir/build.make IEC61850/DO/Settings/ASG/CMakeFiles/ASG.dir/build
.PHONY : ASG/fast

#=============================================================================
# Target rules for targets named ING

# Build rule for target.
ING: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ING
.PHONY : ING

# fast build rule for target.
ING/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Settings/ING/CMakeFiles/ING.dir/build.make IEC61850/DO/Settings/ING/CMakeFiles/ING.dir/build
.PHONY : ING/fast

#=============================================================================
# Target rules for targets named APC

# Build rule for target.
APC: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 APC
.PHONY : APC

# fast build rule for target.
APC/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Settings/Other/APC/CMakeFiles/APC.dir/build.make IEC61850/DO/Settings/Other/APC/CMakeFiles/APC.dir/build
.PHONY : APC/fast

#=============================================================================
# Target rules for targets named CURVE

# Build rule for target.
CURVE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CURVE
.PHONY : CURVE

# fast build rule for target.
CURVE/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Settings/Other/CURVE/CMakeFiles/CURVE.dir/build.make IEC61850/DO/Settings/Other/CURVE/CMakeFiles/CURVE.dir/build
.PHONY : CURVE/fast

#=============================================================================
# Target rules for targets named CSD

# Build rule for target.
CSD: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CSD
.PHONY : CSD

# fast build rule for target.
CSD/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Settings/Other/INFO/CSD/CMakeFiles/CSD.dir/build.make IEC61850/DO/Settings/Other/INFO/CSD/CMakeFiles/CSD.dir/build
.PHONY : CSD/fast

#=============================================================================
# Target rules for targets named DPL

# Build rule for target.
DPL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DPL
.PHONY : DPL

# fast build rule for target.
DPL/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Settings/Other/INFO/DPL/CMakeFiles/DPL.dir/build.make IEC61850/DO/Settings/Other/INFO/DPL/CMakeFiles/DPL.dir/build
.PHONY : DPL/fast

#=============================================================================
# Target rules for targets named LPL

# Build rule for target.
LPL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LPL
.PHONY : LPL

# fast build rule for target.
LPL/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Settings/Other/INFO/LPL/CMakeFiles/LPL.dir/build.make IEC61850/DO/Settings/Other/INFO/LPL/CMakeFiles/LPL.dir/build
.PHONY : LPL/fast

#=============================================================================
# Target rules for targets named SPG

# Build rule for target.
SPG: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SPG
.PHONY : SPG

# fast build rule for target.
SPG/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Settings/SPG/CMakeFiles/SPG.dir/build.make IEC61850/DO/Settings/SPG/CMakeFiles/SPG.dir/build
.PHONY : SPG/fast

#=============================================================================
# Target rules for targets named BCR

# Build rule for target.
BCR: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BCR
.PHONY : BCR

# fast build rule for target.
BCR/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/StatusControl/Status/BCR/CMakeFiles/BCR.dir/build.make IEC61850/DO/StatusControl/Status/BCR/CMakeFiles/BCR.dir/build
.PHONY : BCR/fast

#=============================================================================
# Target rules for targets named DPS

# Build rule for target.
DPS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DPS
.PHONY : DPS

# fast build rule for target.
DPS/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/StatusControl/Status/DPS/CMakeFiles/DPS.dir/build.make IEC61850/DO/StatusControl/Status/DPS/CMakeFiles/DPS.dir/build
.PHONY : DPS/fast

#=============================================================================
# Target rules for targets named INS

# Build rule for target.
INS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 INS
.PHONY : INS

# fast build rule for target.
INS/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/StatusControl/Status/INS/CMakeFiles/INS.dir/build.make IEC61850/DO/StatusControl/Status/INS/CMakeFiles/INS.dir/build
.PHONY : INS/fast

#=============================================================================
# Target rules for targets named SEC

# Build rule for target.
SEC: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SEC
.PHONY : SEC

# fast build rule for target.
SEC/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/StatusControl/Status/SEC/CMakeFiles/SEC.dir/build.make IEC61850/DO/StatusControl/Status/SEC/CMakeFiles/SEC.dir/build
.PHONY : SEC/fast

#=============================================================================
# Target rules for targets named SPS

# Build rule for target.
SPS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SPS
.PHONY : SPS

# fast build rule for target.
SPS/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/StatusControl/Status/SPS/CMakeFiles/SPS.dir/build.make IEC61850/DO/StatusControl/Status/SPS/CMakeFiles/SPS.dir/build
.PHONY : SPS/fast

#=============================================================================
# Target rules for targets named ACD

# Build rule for target.
ACD: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ACD
.PHONY : ACD

# fast build rule for target.
ACD/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/StatusControl/Status/ACD/CMakeFiles/ACD.dir/build.make IEC61850/DO/StatusControl/Status/ACD/CMakeFiles/ACD.dir/build
.PHONY : ACD/fast

#=============================================================================
# Target rules for targets named ACT

# Build rule for target.
ACT: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ACT
.PHONY : ACT

# fast build rule for target.
ACT/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/StatusControl/Status/ACT/CMakeFiles/ACT.dir/build.make IEC61850/DO/StatusControl/Status/ACT/CMakeFiles/ACT.dir/build
.PHONY : ACT/fast

#=============================================================================
# Target rules for targets named BSC

# Build rule for target.
BSC: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BSC
.PHONY : BSC

# fast build rule for target.
BSC/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/StatusControl/Control/BSC/CMakeFiles/BSC.dir/build.make IEC61850/DO/StatusControl/Control/BSC/CMakeFiles/BSC.dir/build
.PHONY : BSC/fast

#=============================================================================
# Target rules for targets named DPC

# Build rule for target.
DPC: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DPC
.PHONY : DPC

# fast build rule for target.
DPC/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/StatusControl/Control/DPC/CMakeFiles/DPC.dir/build.make IEC61850/DO/StatusControl/Control/DPC/CMakeFiles/DPC.dir/build
.PHONY : DPC/fast

#=============================================================================
# Target rules for targets named INC

# Build rule for target.
INC: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 INC
.PHONY : INC

# fast build rule for target.
INC/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/StatusControl/Control/INC/CMakeFiles/INC.dir/build.make IEC61850/DO/StatusControl/Control/INC/CMakeFiles/INC.dir/build
.PHONY : INC/fast

#=============================================================================
# Target rules for targets named ISC

# Build rule for target.
ISC: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ISC
.PHONY : ISC

# fast build rule for target.
ISC/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/StatusControl/Control/ISC/CMakeFiles/ISC.dir/build.make IEC61850/DO/StatusControl/Control/ISC/CMakeFiles/ISC.dir/build
.PHONY : ISC/fast

#=============================================================================
# Target rules for targets named SPC

# Build rule for target.
SPC: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SPC
.PHONY : SPC

# fast build rule for target.
SPC/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/StatusControl/Control/SPC/CMakeFiles/SPC.dir/build.make IEC61850/DO/StatusControl/Control/SPC/CMakeFiles/SPC.dir/build
.PHONY : SPC/fast

#=============================================================================
# Target rules for targets named AnalogValue

# Build rule for target.
AnalogValue: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AnalogValue
.PHONY : AnalogValue

# fast build rule for target.
AnalogValue/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Totalnform/AnalogValue/CMakeFiles/AnalogValue.dir/build.make IEC61850/DO/Totalnform/AnalogValue/CMakeFiles/AnalogValue.dir/build
.PHONY : AnalogValue/fast

#=============================================================================
# Target rules for targets named CtIModels

# Build rule for target.
CtIModels: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CtIModels
.PHONY : CtIModels

# fast build rule for target.
CtIModels/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Totalnform/CtIModels/CMakeFiles/CtIModels.dir/build.make IEC61850/DO/Totalnform/CtIModels/CMakeFiles/CtIModels.dir/build
.PHONY : CtIModels/fast

#=============================================================================
# Target rules for targets named Originator

# Build rule for target.
Originator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Originator
.PHONY : Originator

# fast build rule for target.
Originator/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Totalnform/Originator/CMakeFiles/Originator.dir/build.make IEC61850/DO/Totalnform/Originator/CMakeFiles/Originator.dir/build
.PHONY : Originator/fast

#=============================================================================
# Target rules for targets named Point

# Build rule for target.
Point: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Point
.PHONY : Point

# fast build rule for target.
Point/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Totalnform/Point/CMakeFiles/Point.dir/build.make IEC61850/DO/Totalnform/Point/CMakeFiles/Point.dir/build
.PHONY : Point/fast

#=============================================================================
# Target rules for targets named PulseConfiguration

# Build rule for target.
PulseConfiguration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PulseConfiguration
.PHONY : PulseConfiguration

# fast build rule for target.
PulseConfiguration/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Totalnform/PulseConfiguration/CMakeFiles/PulseConfiguration.dir/build.make IEC61850/DO/Totalnform/PulseConfiguration/CMakeFiles/PulseConfiguration.dir/build
.PHONY : PulseConfiguration/fast

#=============================================================================
# Target rules for targets named Quality

# Build rule for target.
Quality: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Quality
.PHONY : Quality

# fast build rule for target.
Quality/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Totalnform/Quality/CMakeFiles/Quality.dir/build.make IEC61850/DO/Totalnform/Quality/CMakeFiles/Quality.dir/build
.PHONY : Quality/fast

#=============================================================================
# Target rules for targets named RangeConfiguration

# Build rule for target.
RangeConfiguration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RangeConfiguration
.PHONY : RangeConfiguration

# fast build rule for target.
RangeConfiguration/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Totalnform/RangeConfiguration/CMakeFiles/RangeConfiguration.dir/build.make IEC61850/DO/Totalnform/RangeConfiguration/CMakeFiles/RangeConfiguration.dir/build
.PHONY : RangeConfiguration/fast

#=============================================================================
# Target rules for targets named SboClasse

# Build rule for target.
SboClasse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SboClasse
.PHONY : SboClasse

# fast build rule for target.
SboClasse/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Totalnform/SboClasse/CMakeFiles/SboClasse.dir/build.make IEC61850/DO/Totalnform/SboClasse/CMakeFiles/SboClasse.dir/build
.PHONY : SboClasse/fast

#=============================================================================
# Target rules for targets named Unit

# Build rule for target.
Unit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Unit
.PHONY : Unit

# fast build rule for target.
Unit/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Totalnform/Unit/CMakeFiles/Unit.dir/build.make IEC61850/DO/Totalnform/Unit/CMakeFiles/Unit.dir/build
.PHONY : Unit/fast

#=============================================================================
# Target rules for targets named ValWithTrans

# Build rule for target.
ValWithTrans: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ValWithTrans
.PHONY : ValWithTrans

# fast build rule for target.
ValWithTrans/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/DO/Totalnform/ValWithTrans/CMakeFiles/ValWithTrans.dir/build.make IEC61850/DO/Totalnform/ValWithTrans/CMakeFiles/ValWithTrans.dir/build
.PHONY : ValWithTrans/fast

#=============================================================================
# Target rules for targets named CSWI

# Build rule for target.
CSWI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CSWI
.PHONY : CSWI

# fast build rule for target.
CSWI/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/LogicalNodes/CSWI/CMakeFiles/CSWI.dir/build.make IEC61850/LogicalNodes/CSWI/CMakeFiles/CSWI.dir/build
.PHONY : CSWI/fast

#=============================================================================
# Target rules for targets named BaseFuria

# Build rule for target.
BaseFuria: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BaseFuria
.PHONY : BaseFuria

# fast build rule for target.
BaseFuria/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/LogicalNodes/BaseFuria/CMakeFiles/BaseFuria.dir/build.make IEC61850/LogicalNodes/BaseFuria/CMakeFiles/BaseFuria.dir/build
.PHONY : BaseFuria/fast

#=============================================================================
# Target rules for targets named LN

# Build rule for target.
LN: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LN
.PHONY : LN

# fast build rule for target.
LN/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/LogicalNodes/LN/CMakeFiles/LN.dir/build.make IEC61850/LogicalNodes/LN/CMakeFiles/LN.dir/build
.PHONY : LN/fast

#=============================================================================
# Target rules for targets named MMXU

# Build rule for target.
MMXU: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MMXU
.PHONY : MMXU

# fast build rule for target.
MMXU/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/LogicalNodes/MMXU/CMakeFiles/MMXU.dir/build.make IEC61850/LogicalNodes/MMXU/CMakeFiles/MMXU.dir/build
.PHONY : MMXU/fast

#=============================================================================
# Target rules for targets named MSQI

# Build rule for target.
MSQI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MSQI
.PHONY : MSQI

# fast build rule for target.
MSQI/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/LogicalNodes/MSQI/CMakeFiles/MSQI.dir/build.make IEC61850/LogicalNodes/MSQI/CMakeFiles/MSQI.dir/build
.PHONY : MSQI/fast

#=============================================================================
# Target rules for targets named PTOC

# Build rule for target.
PTOC: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PTOC
.PHONY : PTOC

# fast build rule for target.
PTOC/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/LogicalNodes/PTOC/CMakeFiles/PTOC.dir/build.make IEC61850/LogicalNodes/PTOC/CMakeFiles/PTOC.dir/build
.PHONY : PTOC/fast

#=============================================================================
# Target rules for targets named XCBR

# Build rule for target.
XCBR: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 XCBR
.PHONY : XCBR

# fast build rule for target.
XCBR/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/LogicalNodes/XCBR/CMakeFiles/XCBR.dir/build.make IEC61850/LogicalNodes/XCBR/CMakeFiles/XCBR.dir/build
.PHONY : XCBR/fast

#=============================================================================
# Target rules for targets named RDIR

# Build rule for target.
RDIR: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RDIR
.PHONY : RDIR

# fast build rule for target.
RDIR/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/LogicalNodes/RDIR/CMakeFiles/RDIR.dir/build.make IEC61850/LogicalNodes/RDIR/CMakeFiles/RDIR.dir/build
.PHONY : RDIR/fast

#=============================================================================
# Target rules for targets named MySVSB

# Build rule for target.
MySVSB: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MySVSB
.PHONY : MySVSB

# fast build rule for target.
MySVSB/fast:
	$(MAKE) $(MAKESILENT) -f IEC61850/Parser/MySVSB/CMakeFiles/MySVSB.dir/build.make IEC61850/Parser/MySVSB/CMakeFiles/MySVSB.dir/build
.PHONY : MySVSB/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLion.dir/build.make CMakeFiles/CLion.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLion.dir/build.make CMakeFiles/CLion.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CLion.dir/build.make CMakeFiles/CLion.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ACD"
	@echo "... ACT"
	@echo "... APC"
	@echo "... ASG"
	@echo "... AnalogValue"
	@echo "... BCR"
	@echo "... BSC"
	@echo "... BaseClass"
	@echo "... BaseFuria"
	@echo "... BaseType"
	@echo "... BaseVector"
	@echo "... CLion"
	@echo "... CMV"
	@echo "... CSD"
	@echo "... CSWI"
	@echo "... CURVE"
	@echo "... CtIModels"
	@echo "... DEL"
	@echo "... DPC"
	@echo "... DPL"
	@echo "... DPS"
	@echo "... HDEL"
	@echo "... HMV"
	@echo "... HWYE"
	@echo "... INC"
	@echo "... ING"
	@echo "... INS"
	@echo "... ISC"
	@echo "... LN"
	@echo "... LPL"
	@echo "... MMXU"
	@echo "... MSQI"
	@echo "... MV"
	@echo "... MySVSB"
	@echo "... Originator"
	@echo "... PTOC"
	@echo "... Point"
	@echo "... PulseConfiguration"
	@echo "... Quality"
	@echo "... RDIR"
	@echo "... RangeConfiguration"
	@echo "... SAV"
	@echo "... SEC"
	@echo "... SPC"
	@echo "... SPG"
	@echo "... SPS"
	@echo "... SboClasse"
	@echo "... Sequence"
	@echo "... Unit"
	@echo "... ValWithTrans"
	@echo "... WYE"
	@echo "... XCBR"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

